#### **Q1 . Descending Order**

In [12]:
def sorted_array_dsc(string_array):
    try:
        int_array = [int(i) for i in string_array.split()]
        int_array= sorted(int_array)
        return int_array[::-1]
    except ValueError:
        print("Invalid input! Please enter only numbers separated by spaces.")
        return []

if __name__ == "__main__":
   string_array = input("Enter a list of numbers separated by spaces: ")
   sorted_array = sorted_array_dsc(string_array)
   print("Ordered number list in decending order :", sorted_array)


Ordered number list in decending order : []


#### **Numpy Library**

**Creating Numpy Arrays**

In [15]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
print("Original List : ", my_list)

# Convert the list to a numpy array
numpy_array = np.array(my_list)
print("Numpy array : ", numpy_array)

Original List :  [1, 2, 3, 4, 5]
Numpy array :  [1 2 3 4 5]


**Built In Functions**

In [16]:
zeros = np.zeros((3, 3)) # Create a 3x3 matrix of zeros
print("Zeros : \n", zeros)

Zeros : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
ones = np.ones((2, 4)) # Create a 2x4 matrix of ones
print("Ones : \n", ones)    

Ones : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
arange = np.arange(10) # Create a 1D array with values from 0 to 9
print("Arange : ", arange)

Arange :  [0 1 2 3 4 5 6 7 8 9]


In [19]:
random = np.random.rand(2) # Create a 1D array with random values
print("Random : ", random) 

Random :  [0.0112167  0.99776421]


#### **Arithmatic Operators**

**Array Operations**

In [20]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [21]:
sum = a + b
print("Sum : ", sum)

difference = a - b
print("Difference : ", difference)

product = a * b
print("Product : ", product)

quotient = a / b
print("Quotient : ", quotient)

Sum :  [5 7 9]
Difference :  [-3 -3 -3]
Product :  [ 4 10 18]
Quotient :  [0.25 0.4  0.5 ]


**Matrix Multipication**

In [28]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

In [29]:
product = np.dot(matrix_a, matrix_b)
print("Matrix Product : \n", product)

Matrix Product : 
 [[19 22]
 [43 50]]


**Array Indexing and Sicing**

In [33]:
array = np.array([1, 2, 3, 4, 5])
print("Original Array : ", array)

Original Array :  [1 2 3 4 5]


In [34]:
print("Element at index 2 : ", array[2])
print("Elements from index 1 to 4 : ", array[1:4])

Element at index 2 :  3
Elements from index 1 to 4 :  [2 3 4]


**Array Manipulation**

In [38]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
reshaped_array = array.reshape(3, 3)
print("Reshaped Array : ", reshaped_array)

Reshaped Array :  [[1 2 3]
 [4 5 6]
 [7 8 9]]


**Joinning Multiple Arrays Together**

In [39]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
concatenated_array = np.concatenate((array1, array2))
print("Concatenated Array : ", concatenated_array)

Concatenated Array :  [1 2 3 4 5 6]


**Random Number Generation**

In [41]:
random_numbers = np.random.randint(10, 101, 5)
# Generate 5 random numbers from uniform distribution 
# with values between (10, 101)
print("Random Numbers : ", random_numbers)

Random Numbers :  [46 36 18 18 75]


**Q2 . Create a 1D Numpy array with values ranging from 10 to 50.Then,reverse the array.**

In [47]:
import numpy as np

def get_user_input():
    array_input = input('Enter a list of numbers ranging from 10 to 50, separated by spaces : ')
    return array_input

def convert_to_int_array(array_input):
    try:
        int_array = np.array([int(i) for i in array_input.split()])
        if np.any(int_array < 10) or np.any(int_array > 50):
            print('Invalid input! Please enter only numbers ranging from 10 to 50.')
            return []
        print('Array of numbers : ', int_array)
        return int_array
    except ValueError:
        print('Invalid input! Please enter only numbers separated by spaces.')

def convert_to_numpy_array(int_array):
    return np.array(int_array)

def reverse_array(numpy_array):
    return numpy_array[::-1]

def main_menu(int_array):
    if len(int_array) == 0:
        ans = input('Do you want to add numbers again (y/n) : ')
        if ans == 'y':
            start()
        else:
            print('Exiting the program.')
            return 0

def start():
    array_input = get_user_input()
    int_array = convert_to_int_array(array_input)
    numpy_array = convert_to_numpy_array(int_array)
    ans = main_menu(int_array)
    if ans == 0:
        return
    reversed_array = reverse_array(numpy_array)
    print('Reversed Array : ', reversed_array)

if __name__ == "__main__":
    start()
    



Array of numbers :  [11 12 13 14 15]
Reversed Array :  [15 14 13 12 11]


**Q2 . Create a 1D Numpy array with values  from 1 to 12.Then,reshape it into a 3*4 matrix.**

In [48]:
import numpy as np

def get_user_input():
    array_input = input('Enter 12 numbers with spaces : ')
    return array_input

def convert_to_int_array(array_input):
    try:
        int_array = np.array([int(i) for i in array_input.split()])
        if len(int_array) != 12:
            print('Invalid input! Please enter exactly 12 numbers.')
            return []
        print('Array of numbers : ', int_array)
        return int_array
    except ValueError:
        print('Invalid input! Please enter only numbers separated by spaces.')

def main_menu(int_array):
    if len(int_array) == 0:
        ans = input('Do you want to add numbers again (y/n) : ')
        if ans == 'y':
            start()
        else:
            print('Exiting the program.')
            return 0
        
def reshape_array(int_array):
    return int_array.reshape(3, 4)
        
def start():
    array_input = get_user_input()
    int_array = convert_to_int_array(array_input)
    ans = main_menu(int_array)
    if ans == 0:
        return
    reshaped_array = reshape_array(int_array)
    print('Reshaped Array : \n', reshaped_array)

    
if __name__ == "__main__":
    start()

Array of numbers :  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Q4** 

In [57]:
import numpy as np

def create_1D():
    array = np.array([3, 7, 9, 12, 15])
    print('1D Array : ', array)
    return array

def extract_element(array):
    print ('Elements greater than 10 : ',end=' ')
    for i in range(len(array)):
        if(array[i] > 10):
            print(array[i], end=', ')
    print('\b\b')

def start():
    array = create_1D()
    extract_element(array)

if __name__ == "__main__":
    start()

1D Array :  [ 3  7  9 12 15]
Elements greater than 10 :  12, 15


**Q5**

In [58]:
import numpy as np

def create_2D():
    array = np.array([[1, 2, 3], [4, 5, 6]])
    print('2D Array : \n', array)
    return array

def add_10_to_val(array):
    array += 10
    print('Updated Array : \n', array)

def start():
    array = create_2D()
    add_10_to_val(array)

if __name__ == "__main__":
    start()

2D Array : 
 [[1 2 3]
 [4 5 6]]
Updated Array : 
 [[11 12 13]
 [14 15 16]]


### **Pandas**

In [1]:
import pandas as pd

**The Series Data Structure**

In [9]:
data = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}

In [10]:
series = pd.Series(data)
print(series)

a    1
b    2
c    3
d    4
e    5
dtype: int64


**The DataFrame Data Structure**

In [13]:
data = {'Name': ['John', 'Anna', 'Peter', 'Linda'],
        'Location': ['New York', 'Paris', 'Berlin', 'London'],
        'Age': [24, 13, 53, 33]
        }

In [14]:
data_frame = pd.DataFrame(data)
print(data_frame)

    Name  Location  Age
0   John  New York   24
1   Anna     Paris   13
2  Peter    Berlin   53
3  Linda    London   33


**Data Loading and Handeling**

**Reading Data**

In [ ]:
pd.read_csv()
pd.read_excel()
pd.read_sql()

In [18]:
import pandas as pd
df = pd.read_csv('hypertension_dataset.csv')

In [ ]:
print(df.head(10)) # Display the first 10 rows of the dataframe

       Country  Age   BMI  Cholesterol  Systolic_BP  Diastolic_BP  \
0           UK   58  29.5          230          160            79   
1        Spain   34  36.2          201          120            84   
2    Indonesia   73  18.2          173          156            60   
3       Canada   60  20.3          183          122            94   
4       France   73  21.8          296           91            97   
5           UK   44  31.5          293          158           118   
6  South Korea   88  30.9          263          118            62   
7       Canada   25  18.1          151          175           101   
8       Canada   89  19.0          198          102           104   
9       Brazil   33  39.1          268          168            98   

  Smoking_Status  Alcohol_Intake Physical_Activity_Level Family_History  ...  \
0          Never            27.9                     Low            Yes  ...   
1          Never            27.5                    High            Yes  ...   


In [ ]:
print(df.tail(10)) # Display the last 10 rows of the dataframe

             Country  Age   BMI  Cholesterol  Systolic_BP  Diastolic_BP  \
174972  South Africa   34  37.1          260          137            68   
174973           USA   68  23.0          182          126            66   
174974     Argentina   48  26.8          178          104            98   
174975         Japan   66  34.0          179          151            68   
174976        Mexico   24  31.5          160          112           110   
174977         India   51  39.4          266          174            82   
174978     Australia   89  39.0          243          104            94   
174979         India   43  36.5          266          109            98   
174980       Germany   48  18.3          294          134            84   
174981     Argentina   27  22.6          205          111            96   

       Smoking_Status  Alcohol_Intake Physical_Activity_Level Family_History  \
174972        Current            17.6                     Low             No   
174973        

In [23]:
print(df.info()) # Display information about the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 174982 entries, 0 to 174981
Data columns (total 23 columns):
 #   Column                   Non-Null Count   Dtype  
---  ------                   --------------   -----  
 0   Country                  174982 non-null  object 
 1   Age                      174982 non-null  int64  
 2   BMI                      174982 non-null  float64
 3   Cholesterol              174982 non-null  int64  
 4   Systolic_BP              174982 non-null  int64  
 5   Diastolic_BP             174982 non-null  int64  
 6   Smoking_Status           174982 non-null  object 
 7   Alcohol_Intake           174982 non-null  float64
 8   Physical_Activity_Level  174982 non-null  object 
 9   Family_History           174982 non-null  object 
 10  Diabetes                 174982 non-null  object 
 11  Stress_Level             174982 non-null  int64  
 12  Salt_Intake              174982 non-null  float64
 13  Sleep_Duration           174982 non-null  float64
 14  Hear

In [25]:
print(df.shape) # Display the shape of the dataframe - (rows, columns)

(174982, 23)


In [26]:
print(df.columns) # Display the column names of the dataframe

Index(['Country', 'Age', 'BMI', 'Cholesterol', 'Systolic_BP', 'Diastolic_BP',
       'Smoking_Status', 'Alcohol_Intake', 'Physical_Activity_Level',
       'Family_History', 'Diabetes', 'Stress_Level', 'Salt_Intake',
       'Sleep_Duration', 'Heart_Rate', 'LDL', 'HDL', 'Triglycerides',
       'Glucose', 'Gender', 'Education_Level', 'Employment_Status',
       'Hypertension'],
      dtype='object')


In [27]:
print(df.index) # Display the index of the dataframe

RangeIndex(start=0, stop=174982, step=1)


In [28]:
print(df.dtypes) # Display the data types of the columns in the dataframe

Country                     object
Age                          int64
BMI                        float64
Cholesterol                  int64
Systolic_BP                  int64
Diastolic_BP                 int64
Smoking_Status              object
Alcohol_Intake             float64
Physical_Activity_Level     object
Family_History              object
Diabetes                    object
Stress_Level                 int64
Salt_Intake                float64
Sleep_Duration             float64
Heart_Rate                   int64
LDL                          int64
HDL                          int64
Triglycerides                int64
Glucose                      int64
Gender                      object
Education_Level             object
Employment_Status           object
Hypertension                object
dtype: object


In [29]:
print(df.describe()) # Display summary statistics of the dataframe

                 Age            BMI    Cholesterol    Systolic_BP  \
count  174982.000000  174982.000000  174982.000000  174982.000000   
mean       53.493319      27.494672     224.539335     134.505229   
std        20.786353       7.213866      43.361589      26.019268   
min        18.000000      15.000000     150.000000      90.000000   
25%        36.000000      21.200000     187.000000     112.000000   
50%        54.000000      27.500000     225.000000     135.000000   
75%        71.000000      33.700000     262.000000     157.000000   
max        89.000000      40.000000     299.000000     179.000000   

        Diastolic_BP  Alcohol_Intake   Stress_Level    Salt_Intake  \
count  174982.000000   174982.000000  174982.000000  174982.000000   
mean       89.450315       14.991069       5.013041       8.482757   
std        17.310789        8.652624       2.582341       3.750074   
min        60.000000        0.000000       1.000000       2.000000   
25%        74.000000        

**Q6**

In [34]:
data = {
    'Name': ['Alice', 'Bob', 'Claire'],
    'Age': [25, 30, 35],
    'Gender': ['F', 'M', 'F']
}
df = pd.DataFrame(data)
print(df)

print(df.head())
print(df.tail(10))
print(df.info())
print(df.shape)
print(df.columns)
print(df.index)
print(df.dtypes)
print(df.describe())

     Name  Age Gender
0   Alice   25      F
1     Bob   30      M
2  Claire   35      F
     Name  Age Gender
0   Alice   25      F
1     Bob   30      M
2  Claire   35      F
     Name  Age Gender
0   Alice   25      F
1     Bob   30      M
2  Claire   35      F
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   Gender  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
None
(3, 3)
Index(['Name', 'Age', 'Gender'], dtype='object')
RangeIndex(start=0, stop=3, step=1)
Name      object
Age        int64
Gender    object
dtype: object
        Age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0


In [38]:
data = {
    'Name': ['Alice', 'Bob', 'Claire'],
    'Age': [25, 30, 28],
    'Gender': ['Female', 'Male', 'Female']
}
df = pd.DataFrame(data)

df_shape = df.shape
print('Shape of the dataframe : ', df_shape)

Shape of the dataframe :  (3, 3)


**From the DataFrame created above,filter and display rows where Age is greater than 25.**

In [39]:
filtered_df = df[df['Age'] > 25]
print('Filtered Dataframe  : \n', filtered_df)

Filtered Dataframe  : 
      Name  Age  Gender
1     Bob   30    Male
2  Claire   28  Female


**Add a new coulmn salary to the DataFrame with values [50000,60000,55000]**

In [40]:
df['salary'] = [50000, 60000, 55000]
print('Updated Dataframe : \n', df)

Updated Dataframe : 
      Name  Age  Gender  salary
0   Alice   25  Female   50000
1     Bob   30    Male   60000
2  Claire   28  Female   55000


**Group the DataFrame by Gender and calculate the average Age for each gender**

In [42]:
grouped_data = df.groupby('Gender')['Age'].mean()
print('Mean Age of people group by gender : ')
print(grouped_data)

Mean Age of people group by gender : 
Gender
Female    26.5
Male      30.0
Name: Age, dtype: float64


**Sort the DataFrame by Salary in descending order**

In [47]:
sorted_dataframe = df.sort_values(by='salary', ascending=False)
print('Sorted Dataframe : \n', sorted_dataframe)

Sorted Dataframe : 
      Name  Age  Gender  salary
1     Bob   30    Male   60000
2  Claire   28  Female   55000
0   Alice   25  Female   50000
